# Generated by Django 5.1.5 on 2025-02-26 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_remove_privatemessage_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='privatemessage',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
    ]
