# Generated by Django 5.1.5 on 2025-03-04 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_privatemessage_is_online'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.TextField()),
                ('feedback', models.CharField(max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
