# Generated by Django 5.1.5 on 2025-03-04 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_feedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
